### ISSUE TITLE
Plugin not executed

### ISSUE THREAD

**Issue by muuvmuuv** [larsenwork/postcss-easing-gradients#11]
I use GatsbyJS for my site and added this plugin to my `postcss.config.js` but it does not work or even gets executed. I tried to add `console.log` directly to the code in node_modules and also tested the same with `autoprefixer` but this plugin prints nothing.

Here is a sandbox:
https://codesandbox.io/s/gatsby-starter-default-y8slq?fontsize=14

**Comment by muuvmuuv** [comment]
Okay, it seems it is just not working with Scss.

**Comment by apriljunge** [comment]
@muuvmuuv Can you close this?
