### ISSUE TITLE
Not working with postcss-js?

### ISSUE THREAD

**Issue by sedlukha** [larsenwork/postcss-easing-gradients#5]
It seems easing-gradients isn't working with postcss-js:

```js
import postcssJs from 'postcss-js'
import rtlcss from 'rtlcss'
import gradients from 'postcss-easing-gradients'

const process = postcssJs.sync([ rtlcss, gradients ])

const css = {
  left: '5px',
  background: 'linear-gradient(to bottom, black, cubic-bezier(0.48, 0.3, 0.64, 1), transparent)'
}

console.log(process(css))
/*
{
  right: "5px",
  background: "linear-gradient(to bottom, black, cubic-bezier(0.48, 0.3, 0.64, 1), transparent)"
}
*/
```

As you can see it's not webpack or postcss-js issue, because rtlcss works fine.

**Comment by phyllisstein** [comment]
Something similar seems to be happening with [`babel-plugin-styled-components-postcss`](https://github.com/timgrafton/babel-plugin-styled-components-postcss)---Autoprefixer and other plugins are applying their transformations, but the gradient is ignored:

```js
// In

export const Hero = styled.header`
  background: linear-gradient(red, ease, green);
  color: ${ ({ theme }) => theme.palette.rgb.white };
  color: twitter-color;
  height: 100vh;
`
```

```js
// Out

export const Hero = styled.header`
  background: -webkit-gradient(linear, left top, left bottom, from(red), color-stop(ease), to(green));
  background: linear-gradient(red, ease, green);
  color: ${({
  theme
}) => theme.palette.rgb.white};
  color: #1da1f2;
  height: 100vh;
`;
```

Works fine with `postcss-cli`, but falls over when applied by JS.

**Comment by phyllisstein** [comment]
After a little investigation, my guess is that the issue on my end was that `postcss-easing-gradients` walks _rules_, but the Babel plugin was just feeding PostCSS raw declarations. I suspect @sedlukha might be seeing the same problem, since it doesn't look like the CSS declarations for `postcss-js` are wrapped in rules either.

**Comment by alexandrutasica** [comment]
Hello,
I know this is an old topic. 
Did you solve the problem? Can you please share the solution?

Thank you.
